repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
      
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.8
      args:
        - --line-length=120
        - --experimental-string-processing

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
        - --config=.flake8
  
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args:
        - --rcfile=.pylintrc