RunConfig:
  Name: OPERA-DSWX-NI-PGE-TEST-CONFIG
  Groups:
    PGE:
      PGENameGroup:
        PGEName: DSWX_NI_PGE
      InputFilesGroup:
        InputFilePaths:
        - dswx_ni_pge_test/input_dir
      DynamicAncillaryFilesGroup:
        AncillaryFileMap:
          dem_file: dswx_ni_pge_test/input_dir/dem.tif
          hand_file: dswx_ni_pge_test/input_dir/hand.tif
          reference_water_file: dswx_ni_pge_test/input_dir/reference_water.tif
          world_cover: dswx_ni_pge_test/input_dir/worldcover.tif
          shoreline_shapefile: dswx_ni_pge_test/input_dir/shoreline.shp
      ProductPathGroup:
        OutputProductPath: dswx_ni_pge_test/output_dir
        ScratchPath: dswx_ni_pge_test/scratch_dir
      PrimaryExecutable:
        ProductIdentifier: DSWX_NI
        ProductVersion: "1.0"
        ProgramPath: /bin/echo
        ProgramOptions:
        - hello world > dswx_ni_pge_test/output_dir/OPERA_L3_DSWx-NI_T18MVA_20200702T231843Z_20230317T190549Z_v0.1_B01_WTR.tif;
        - /bin/echo hello world > dswx_ni_pge_test/output_dir/OPERA_L3_DSWx-NI_T18MVA_20200702T231843Z_20230317T190549Z_v0.1_B02_BWTR.tif;
        - /bin/echo hello world > dswx_ni_pge_test/output_dir/OPERA_L3_DSWx-NI_T18MVA_20200702T231843Z_20230317T190549Z_v0.1_B03_CONF.tif;
        - /bin/echo DSWx-NI invoked with RunConfig
        ErrorCodeBase: 400000
        SchemaPath: pge/dswx_ni/schema/dswx_ni_sas_schema.yaml
        AlgorithmParametersSchemaPath: pge/dswx_ni/schema/algorithm_parameters_ni_schema.yaml
        IsoTemplatePath: 
      QAExecutable:
        Enabled: false
        ProgramPath: null
        ProgramOptions: []
      DebugLevelGroup:
        DebugSwitch: false
        ExecuteViaShell: true
    SAS:
      runconfig:
        name: dswx_ni_workflow_default
        groups:
          pge_name_group:
            pge_name: DSWX_NI_PGE
          input_file_group:
            input_file_path:
            - dswx_ni_pge_test/input_dir
          dynamic_ancillary_file_group:
            dem_file: dswx_ni_pge_test/input_dir/dem.tif
            dem_file_description: DEM
            worldcover_file: dswx_ni_pge_test/input_dir/worldcover.tif
            reference_water_file: dswx_ni_pge_test/input_dir/reference_water.tif
            shoreline_shapefile: dswx_ni_pge_test/input_dir/shoreline.shp
            hand_file: dswx_ni_pge_test/input_dir/hand.tif
            algorithm_parameters: dswx_ni_pge_test/input_dir/test_dswx_ni_algorithm_parameters.yaml
          static_ancillary_file_group:
            static_ancillary_inputs_flag: True
            mgrs_database_file: dswx_ni_pge_test/input_dir/MGRS_tile.sqlite
            mgrs_collection_database_file: dswx_ni_pge_test/input_dir/MGRS_tile_collection.sqlite
          primary_executable:
            product_type: dswx_ni
          product_path_group:
            product_path: dswx_ni_pge_test/output_dir
            scratch_path: dswx_ni_pge_test/scratch_dir
            sas_output_path: dswx_ni_pge_test/output_dir
          log_file: dswx_ni_pge_test/output_dir/test_log.log
