RunConfig:
  Name: OPERA-DISP-S1-PGE-INT-TEST-CONFIG

  Groups:
    PGE:
      PGENameGroup:
        PGEName: DISP_S1_PGE

      InputFilesGroup:
        InputFilePaths:
          - /home/mamba/input_dir/input_slcs/compressed_t042_088905_iw1_20221107_20230506.h5
          - /home/mamba/input_dir/input_slcs/compressed_t042_088906_iw1_20221107_20230506.h5
          - /home/mamba/input_dir/input_slcs/t042_088905_iw1_20221119.h5
          - /home/mamba/input_dir/input_slcs/t042_088906_iw1_20221119.h5
          - /home/mamba/input_dir/input_slcs/t042_088905_iw1_20221201.h5
          - /home/mamba/input_dir/input_slcs/t042_088906_iw1_20221201.h5
          - /home/mamba/input_dir/input_slcs/t042_088905_iw1_20221213.h5
          - /home/mamba/input_dir/input_slcs/t042_088906_iw1_20221213.h5

      DynamicAncillaryFilesGroup:
        AncillaryFileMap:
          dem_file: /home/mamba/input_dir/dynamic_ancillary_files/dem.tif
          mask_file: /home/mamba/input_dir/dynamic_ancillary_files/watermask.flg
          amplitude_dispersion_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_dispersion.tif
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_dispersion.tif
          amplitude_mean_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_mean.tif
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_mean.tif
          static_layers_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/static_layers_t042_088905_iw1.h5
            - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/static_layers_t042_088906_iw1.h5
          ionosphere_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0060.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0180.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0300.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0420.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0540.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0660.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0780.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0900.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1020.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1140.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1260.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1380.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1500.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1620.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1860.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1980.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg2100.23i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3230.22i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3350.22i.Z
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3470.22i.Z
          troposphere_files: []
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20221119_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20221201_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20221213_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230106_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230118_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230130_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230211_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230223_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230307_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230319_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230331_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230412_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230424_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230506_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230518_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230530_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230611_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230705_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230717_14.grb
#            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230729_14.grb

      ProductPathGroup:
        OutputProductPath: /home/mamba/output_dir
        ScratchPath: /home/mamba/scratch_dir

      PrimaryExecutable:
        ProductIdentifier: DISP_S1
        ProductVersion: "0.2"
        ProgramPath: disp-s1
        ProgramOptions: []
        ErrorCodeBase: 500000
        SchemaPath: /home/mamba/opera/pge/disp_s1/schema/disp_s1_sas_schema.yaml
        AlgorithmParametersSchemaPath: /home/mamba/opera/pge/disp_s1/schema/algorithm_parameters_disp_s1_schema.yaml
        IsoTemplatePath: /home/mamba/opera/pge/disp_s1/templates/OPERA_ISO_metadata_L3_DISP_S1_template.xml.jinja2

      QAExecutable:
        Enabled: False
        ProgramPath:
        ProgramOptions: []

      DebugLevelGroup:
        DebugSwitch: False
        ExecuteViaShell: False
    SAS:
      input_file_group:
        cslc_file_list:
          - /home/mamba/input_dir/input_slcs/compressed_t042_088905_iw1_20221107_20230506.h5
          - /home/mamba/input_dir/input_slcs/compressed_t042_088906_iw1_20221107_20230506.h5
          - /home/mamba/input_dir/input_slcs/t042_088905_iw1_20221119.h5
          - /home/mamba/input_dir/input_slcs/t042_088906_iw1_20221119.h5
          - /home/mamba/input_dir/input_slcs/t042_088905_iw1_20221201.h5
          - /home/mamba/input_dir/input_slcs/t042_088906_iw1_20221201.h5
          - /home/mamba/input_dir/input_slcs/t042_088905_iw1_20221213.h5
          - /home/mamba/input_dir/input_slcs/t042_088906_iw1_20221213.h5

        frame_id: 11114
      dynamic_ancillary_file_group:
        algorithm_parameters_file: /home/mamba/input_dir/algorithm_parameters_forward.yaml
        amplitude_dispersion_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_dispersion.tif
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_dispersion.tif
        amplitude_mean_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_mean.tif
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_mean.tif
        static_layers_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/static_layers_t042_088905_iw1.h5
          - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/static_layers_t042_088906_iw1.h5
        mask_file: /home/mamba/input_dir/dynamic_ancillary_files/watermask.flg
        dem_file: /home/mamba/input_dir/dynamic_ancillary_files/dem.tif
        ionosphere_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0060.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0180.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0300.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0420.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0540.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0660.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0780.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0900.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1020.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1140.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1260.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1380.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1500.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1620.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1860.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1980.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg2100.23i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3230.22i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3350.22i.Z
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3470.22i.Z
        troposphere_files: []
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20221119_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20221201_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20221213_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230106_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230118_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230130_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230211_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230223_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230307_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230319_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230331_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230412_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230424_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230506_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230518_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230530_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230611_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230705_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230717_14.grb
#          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N30_N40_W120_W110_20230729_14.grb
      static_ancillary_file_group:
        frame_to_burst_json: /home/mamba/input_dir/opera-s1-disp-frame-to-burst.json
      primary_executable:
        product_type: DISP_S1_FORWARD
      product_path_group:
        product_path: /home/mamba/output_dir
        scratch_path: /home/mamba/scratch_dir
        sas_output_path: /home/mamba/output_dir
        product_version: "0.2"
        save_compressed_slc: true
      worker_settings:
        gpu_enabled: true
        n_workers: 4
        threads_per_worker: 2
        n_parallel_bursts: 1
        block_shape:
          - 512
          - 512
      log_file: /home/mamba/output_dir/sas_logfile.log
