RunConfig:
  Name: OPERA-DISP-S1-PGE-INT-TEST-CONFIG

  Groups:
    PGE:
      PGENameGroup:
        PGEName: DISP_S1_PGE

      InputFilesGroup:
        InputFilePaths:
          - /home/mamba/input_dir/input_slcs/OPERA_L2_COMPRESSED-CSLC-S1_T042-088905-IW1_20221107T000000Z_20221107T000000Z_20230506T000000Z_20230507T000000Z_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_COMPRESSED-CSLC-S1_T042-088906-IW1_20221107T000000Z_20221107T000000Z_20230506T000000Z_20230507T000000Z_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088905-IW1_20221119T000000Z_20221120T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088906-IW1_20221119T000000Z_20221120T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088905-IW1_20221201T000000Z_20221202T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088906-IW1_20221201T000000Z_20221202T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088905-IW1_20221213T000000Z_20221214T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088906-IW1_20221213T000000Z_20221214T000000Z_S1A_VV_v1.0.h5

      DynamicAncillaryFilesGroup:
        AncillaryFileMap:
          dem_file: /home/mamba/input_dir/dynamic_ancillary_files/dem.tif
          mask_file: /home/mamba/input_dir/dynamic_ancillary_files/watermask.tif
          amplitude_dispersion_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_dispersion.tif
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_dispersion.tif
          amplitude_mean_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_mean.tif
            - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_mean.tif
          static_layers_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/OPERA_L2_CSLC-S1-STATIC_T042-088905-IW1_20140403_S1A_VV_v1.0.h5
            - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/OPERA_L2_CSLC-S1-STATIC_T042-088906-IW1_20140403_S1A_VV_v1.0.h5
          ionosphere_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0060.23i
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1860.23i
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3110.22i
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3230.22i
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3350.22i
            - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3470.22i
          troposphere_files:
            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221107_14.grb
            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221119_14.grb
            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221201_14.grb
            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221213_14.grb
            - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20230506_14.grb

      ProductPathGroup:
        OutputProductPath: /home/mamba/output_dir
        ScratchPath: /home/mamba/scratch_dir

      PrimaryExecutable:
        ProductIdentifier: DISP_S1
        ProductVersion: "0.2"
        ProgramPath: disp-s1
        ProgramOptions:
          - run
        ErrorCodeBase: 500000
        SchemaPath: /home/mamba/opera/pge/disp_s1/schema/disp_s1_sas_schema.yaml
        AlgorithmParametersSchemaPath: /home/mamba/opera/pge/disp_s1/schema/algorithm_parameters_disp_s1_schema.yaml
        IsoTemplatePath: /home/mamba/opera/pge/disp_s1/templates/OPERA_ISO_metadata_L3_DISP_S1_template.xml.jinja2

      QAExecutable:
        Enabled: True
        ProgramPath: /home/mamba/opera/.ci/scripts/disp_s1/compare_disp_s1_products.sh
        ProgramOptions: []

      DebugLevelGroup:
        DebugSwitch: False
        ExecuteViaShell: False
    SAS:
      input_file_group:
        cslc_file_list:
          - /home/mamba/input_dir/input_slcs/OPERA_L2_COMPRESSED-CSLC-S1_T042-088905-IW1_20221107T000000Z_20221107T000000Z_20230506T000000Z_20230507T000000Z_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_COMPRESSED-CSLC-S1_T042-088906-IW1_20221107T000000Z_20221107T000000Z_20230506T000000Z_20230507T000000Z_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088905-IW1_20221119T000000Z_20221120T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088906-IW1_20221119T000000Z_20221120T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088905-IW1_20221201T000000Z_20221202T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088906-IW1_20221201T000000Z_20221202T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088905-IW1_20221213T000000Z_20221214T000000Z_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/input_slcs/OPERA_L2_CSLC-S1_T042-088906-IW1_20221213T000000Z_20221214T000000Z_S1A_VV_v1.0.h5

        frame_id: 11114
      dynamic_ancillary_file_group:
        algorithm_parameters_file: /home/mamba/runconfig/opera_pge_disp_s1_r4.2_gamma_algorithm_parameters_forward.yaml
        amplitude_dispersion_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_dispersion.tif
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_dispersion.tif
        amplitude_mean_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088905_iw1_amp_mean.tif
          - /home/mamba/input_dir/dynamic_ancillary_files/ps_files/t042_088906_iw1_amp_mean.tif
        static_layers_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/OPERA_L2_CSLC-S1-STATIC_T042-088905-IW1_20140403_S1A_VV_v1.0.h5
          - /home/mamba/input_dir/dynamic_ancillary_files/static_layers/OPERA_L2_CSLC-S1-STATIC_T042-088906-IW1_20140403_S1A_VV_v1.0.h5
        mask_file: /home/mamba/input_dir/dynamic_ancillary_files/watermask.tif
        dem_file: /home/mamba/input_dir/dynamic_ancillary_files/dem.tif
        ionosphere_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg0060.23i
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg1860.23i
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3110.22i
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3230.22i
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3350.22i
          - /home/mamba/input_dir/dynamic_ancillary_files/ionosphere_files/jplg3470.22i
        troposphere_files:
          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221107_14.grb
          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221119_14.grb
          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221201_14.grb
          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20221213_14.grb
          - /home/mamba/input_dir/dynamic_ancillary_files/troposphere_files/ERA5_N36_N41_W124_W118_20230506_14.grb

      static_ancillary_file_group:
        frame_to_burst_json:
        reference_date_database_json:
      primary_executable:
        product_type: DISP_S1_FORWARD
      product_path_group:
        product_path: /home/mamba/output_dir
        scratch_path: /home/mamba/scratch_dir
        sas_output_path: /home/mamba/output_dir
        product_version: "0.2"
        save_compressed_slc: true
      worker_settings:
        gpu_enabled: true
        threads_per_worker: 1
        n_parallel_bursts: 1
        block_shape:
          - 512
          - 512
      log_file: /home/mamba/output_dir/sas_logfile.log
