name: Pylint Lint

on: [push, pull_request]

jobs:
  pylint-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Pylint Lint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        args: pylint **/*.py --rcfile=.pylintrc